"""
Prompt templates for Deep Research AI.

This package contains all prompt templates used by the research modules.
"""

# System prompts
from .system_prompts import (
    RESEARCH_SYSTEM_PROMPT,
    QUERY_ANALYSIS_SYSTEM_PROMPT,
    REASONING_SYSTEM_PROMPT,
    VERIFICATION_SYSTEM_PROMPT,
    OUTPUT_SYSTEM_PROMPT,
)

# Query understanding prompts
from .query_prompts import (
    QUERY_ANALYSIS_PROMPT,
    QUERY_DECOMPOSITION_PROMPT,
    ENTITY_EXTRACTION_PROMPT,
    QUERY_CLARIFICATION_PROMPT,
    QUERY_VALIDATION_PROMPT,
)

# Search prompts
from .search_prompts import (
    SEARCH_QUERY_GENERATION_PROMPT,
    RESULT_RELEVANCE_PROMPT,
    CONTENT_EXTRACTION_PROMPT,
    SOURCE_EVALUATION_PROMPT,
)

# Reasoning prompts
from .reasoning_prompts import (
    CHAIN_OF_THOUGHT_PROMPT,
    INFORMATION_SYNTHESIS_PROMPT,
    COMPARISON_ANALYSIS_PROMPT,
    EVIDENCE_EVALUATION_PROMPT,
    CONCLUSION_GENERATION_PROMPT,
)

# Verification prompts
from .verification_prompts import (
    CROSS_REFERENCE_PROMPT,
    SOURCE_CREDIBILITY_PROMPT,
    CONFLICT_DETECTION_PROMPT,
    FACT_CHECK_PROMPT,
    BIAS_DETECTION_PROMPT,
)

# Citation prompts
from .citation_prompts import (
    CITATION_GENERATION_PROMPT,
    SOURCE_ATTRIBUTION_PROMPT,
    REFERENCE_LIST_PROMPT,
    INLINE_CITATION_PROMPT,
    CITATION_VALIDATION_PROMPT,
    SOURCE_METADATA_PROMPT,
    FOOTNOTE_GENERATION_PROMPT,
)

# Output generation prompts
from .output_prompts import (
    REPORT_GENERATION_PROMPT,
    SUMMARY_GENERATION_PROMPT,
    ANSWER_FORMATTING_PROMPT,
    VISUALIZATION_SUGGESTION_PROMPT,
    MULTI_FORMAT_OUTPUT_PROMPT,
    RESPONSE_QUALITY_PROMPT,
    FOLLOWUP_QUESTIONS_PROMPT,
    EXPORT_FORMAT_PROMPT,
)

# Error handling prompts
from .error_prompts import (
    ERROR_ANALYSIS_PROMPT,
    GRACEFUL_DEGRADATION_PROMPT,
    USER_ERROR_MESSAGE_PROMPT,
    RETRY_STRATEGY_PROMPT,
    ERROR_RECOVERY_PROMPT,
    FALLBACK_CONTENT_PROMPT,
    SYSTEM_HEALTH_PROMPT,
)

__all__ = [
    # System prompts
    "RESEARCH_SYSTEM_PROMPT",
    "QUERY_ANALYSIS_SYSTEM_PROMPT",
    "REASONING_SYSTEM_PROMPT",
    "VERIFICATION_SYSTEM_PROMPT",
    "OUTPUT_SYSTEM_PROMPT",
    
    # Query prompts
    "QUERY_ANALYSIS_PROMPT",
    "QUERY_DECOMPOSITION_PROMPT",
    "ENTITY_EXTRACTION_PROMPT",
    "QUERY_CLARIFICATION_PROMPT",
    "QUERY_VALIDATION_PROMPT",
    
    # Search prompts
    "SEARCH_QUERY_GENERATION_PROMPT",
    "RESULT_RELEVANCE_PROMPT",
    "CONTENT_EXTRACTION_PROMPT",
    "SOURCE_EVALUATION_PROMPT",
    
    # Reasoning prompts
    "CHAIN_OF_THOUGHT_PROMPT",
    "INFORMATION_SYNTHESIS_PROMPT",
    "COMPARISON_ANALYSIS_PROMPT",
    "EVIDENCE_EVALUATION_PROMPT",
    "CONCLUSION_GENERATION_PROMPT",
    
    # Verification prompts
    "CROSS_REFERENCE_PROMPT",
    "SOURCE_CREDIBILITY_PROMPT",
    "CONFLICT_DETECTION_PROMPT",
    "FACT_CHECK_PROMPT",
    "BIAS_DETECTION_PROMPT",
    
    # Citation prompts
    "CITATION_GENERATION_PROMPT",
    "SOURCE_ATTRIBUTION_PROMPT",
    "REFERENCE_LIST_PROMPT",
    "INLINE_CITATION_PROMPT",
    "CITATION_VALIDATION_PROMPT",
    "SOURCE_METADATA_PROMPT",
    "FOOTNOTE_GENERATION_PROMPT",
    
    # Output prompts
    "REPORT_GENERATION_PROMPT",
    "SUMMARY_GENERATION_PROMPT",
    "ANSWER_FORMATTING_PROMPT",
    "VISUALIZATION_SUGGESTION_PROMPT",
    "MULTI_FORMAT_OUTPUT_PROMPT",
    "RESPONSE_QUALITY_PROMPT",
    "FOLLOWUP_QUESTIONS_PROMPT",
    "EXPORT_FORMAT_PROMPT",
    
    # Error prompts
    "ERROR_ANALYSIS_PROMPT",
    "GRACEFUL_DEGRADATION_PROMPT",
    "USER_ERROR_MESSAGE_PROMPT",
    "RETRY_STRATEGY_PROMPT",
    "ERROR_RECOVERY_PROMPT",
    "FALLBACK_CONTENT_PROMPT",
    "SYSTEM_HEALTH_PROMPT",
]
